from argparse import _SubParsersAction
from typing import Optional

from app.objects import GitTag
from app.repository import GitRepository
from app.repository.config import get_user_from_config

from .command import cmd
from .show_ref import show_ref


def setup_parser(subparsers: _SubParsersAction) -> None:
    parser = subparsers.add_parser("tag", help="List and create tags")

    group = parser.add_mutually_exclusive_group()
    group.add_argument("--list", "-l", action="store_true", help="List all tags")
    group.add_argument(
        "-a",
        action="store_true",
        dest="create_tag_object",
        help="Create an annotated tag",
    )
    parser.add_argument("-m", metavar="message", dest="message", help="Tag message")
    parser.add_argument("name", nargs="?", help="Tag name")
    parser.add_argument(
        "object", default="HEAD", nargs="?", help="Object the tag points to"
    )

    parser.set_defaults(func=cmd_tag)


@cmd(req_repo=True)
def cmd_tag(args, repo: GitRepository) -> None:
    if args.list:
        tag_list(repo)
    elif args.name:
        tag_create(
            repo,
            args.name,
            args.object,
            create_tag_object=args.create_tag_object,
            message=args.message,
        )
    else:
        tag_list(repo)


def tag_list(repo: GitRepository):
    tags = repo.refs.list()["tags"]
    if isinstance(tags, dict):
        show_ref(tags, with_hash=False)


def tag_create(
    repo: GitRepository,
    name: str,
    ref: str,
    create_tag_object: bool = False,
    message: Optional[str] = None,
):
    sha = repo.objects.find(ref)

    if create_tag_object or message:
        tag = GitTag()
        tag.kvlm.set(b"object", sha.encode())
        tag.kvlm.set(b"type", b"commit")
        tag.kvlm.set(b"tag", name.encode())
        tag.kvlm.set(b"tagger", get_user_from_config(repo.config).encode())

        if message is None:
            message = "A default tag generated by mgit (you can customize this message with -m)"
        tag.kvlm.set_message(message.encode("utf-8"))

        tag_sha = repo.objects.write(tag)

        repo.refs.create("tags", name, sha=tag_sha)
    else:
        repo.refs.create("tags", name, sha=sha)
